# Global properties go here
spring:
   profiles:
      active: test
---
# Test properties go here
spring:
   profiles: test
---
# Dev properties go here
spring:
   profiles: dev
# set debug to get spring to log the classpath (and other things) on startup
debug: true
---
# UAT properties go here
spring:
   profiles: uat